### ISSUE TITLE
another LINE here

### ISSUE THREAD

**Issue by tpunix** [wishstudio/flinux#16]
http://www.cnblogs.com/gussing/archive/2011/09/04/2165968.html

**Comment by wishstudio** [comment]
I briefly browsed your blog post and get the impression that your project is a derivation of the project LINE.
I have touched about every aspect about LINE. Although it works very reliably (which is awesome for a project discontinued for more than a decade), it still has major issues towards completing:
- It works by trapping "int  80h" exceptions, this will not work for x64 as the "syscall" instruction is not trappable.
- It does not consider the segment register issues (https://github.com/wishstudio/flinux/wiki/Incompatibilities), so it will only run ancient libc and applications

BTW, I'm closing this as it is not a real issue.
