### ISSUE TITLE
Performance Comparison

### ISSUE THREAD

**Issue by yxliang01** [wishstudio/flinux#25]
Hello guys, actually this is not an issue. Nowadays, I am just wondering the performance of Flinux. As we all know, performance is one of the main concern for the program similar to emulator. (I have no idea about how to test it) By the way, I am curious that what motivates the author to make this, hope that you can share your developing experience if you are the author. Thank You. ^_^

**Comment by littmus** [comment]
I don't know this is a good comparison, but just used python for-loop.
Local Windows : 
C:\Users>python -m timeit "for i in range(10**6):pass"
10 loops, best of 3: 21.3 msec per loop
flinux :
[root@ForeignLinux bin]# python2 -m timeit "for i in range(10**6):pass"
10 loops, best of 3: 39.1 msec per loop

**Comment by wishstudio** [comment]
The performance of a dynamic binary translation system varies a lot across use cases. It's better to use a comprehensive test suite (for example SPEC2000) for testing the performance characteristics. It would awesome if you could try to get it running on flinux.

**Comment by wishstudio** [comment]
Besides, you can join the freenode IRC channel #flinux if you want to have a chat :)

**Comment by yxliang01** [comment]
@wishstudio nice~ I will join it when I'm free ^_^ 
@littmus your test is just indicating the difference in speed between native code and translated code. btw, thanks~ just like what Mr.Sun said,  it would be awesome if you can try running geekbench on Win native, Flinux, Cygwin and Mingw. Sorry that I don't have time to do it.
