### ISSUE TITLE
Crash when I use curl

### ISSUE THREAD

**Issue by lumiit-adam** [wishstudio/flinux#29]
I went through the developer's guide. Everything is OK until I begin use “curl”. flinux crashed, and also crashed when I use "pacman -Syu". I think it maybe occured when it try to visit the internet? My OS is win 7 64bit.

**Comment by wishstudio** [comment]
Please post your flog output (use a pastebin service) and detailed console output so we can investigate. Thank you.

**Comment by wishstudio** [comment]
Confirmed here.
curl crashes on large webpages. It's a shame that I only tested `curl google.com` and never catch this bug. Will work on it.

**Comment by wishstudio** [comment]
Likely to be console issues with UTF-8 handling.
I can get it running by adding `-o filename` parameter to save webpage content to a file instead of writing to the console. Could you please try it?

**Comment by lumiit-adam** [comment]
Yes, as you said, I test curl with -o option and it seems OK. Thanks for your reply.

**Comment by wishstudio** [comment]
Crashing when writing UTF-8 content to console should be fixed in commit 70e349a46f303e4207a37a364d5e7000c5ad89dc.
