### ISSUE TITLE
pacman download timeout due to rt_sigaction not implemented

### ISSUE THREAD

**Issue by bojieli** [wishstudio/flinux#30]
When a file download in pacman takes more than 10 seconds, it would timeout. Pacman relies on <code>rt_sigaction</code> to get download progress (the signal number is <code>SIGPIPE</code>).

Note: I intentionally use a slow package mirror to illustrate this bug.

<pre>
[root@ForeignLinux /]# pacman -S vim
resolving dependencies...
looking for conflicting packages...

Packages (8) gpm-1.20.7-4  libyaml-0.1.6-1  lua-5.2.3-1  python2-2.7.9-1  ruby-2.2.1-1  sqlite-3.8.8.3-1
             vim-runtime-7.4.617-1  vim-7.4.617-1

Total Download Size:    21.37 MiB
Total Installed Size:  120.36 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages ...
 gpm-1.20.7-4-i686                              120.8 KiB  0.00B/s 00:00 [########################################] 100%
 sqlite-3.8.8.3-1-i686                          501.7 KiB  0.00B/s 00:00 [########################################] 100%
error: failed retrieving file 'vim-runtime-7.4.617-1-i686.pkg.tar.xz' from mirror.rackspace.com : Operation too slow. Le
ss than 1 bytes/sec transferred the last 10 seconds
warning: failed to retrieve some files
error: failed retrieving file 'libyaml-0.1.6-1-i686.pkg.tar.xz' from mirror.rackspace.com : Operation too slow. Less tha
n 1 bytes/sec transferred the last 10 seconds
warning: failed to retrieve some files
 ruby-2.2.1-1-i686                                4.1 MiB  0.00B/s 00:00 [########################################] 100%
</pre>

Log excerpt:

<pre>
(II) poll(0x0039f284, 1, 0)
(II) sys_clock_gettime(1, 0x0039f2a4)
(II) sys_clock_gettime(1, 0x0039f1a4)
(II) sys_clock_gettime(6, 0x0039f074)
(II) sys_clock_gettime(1, 0x0039f234)
(II) sys_clock_gettime(1, 0x0039f224)
(II) sys_clock_gettime(1, 0x0039f224)
(II) sys_clock_gettime(6, 0x0039f0f4)
(II) rt_sigaction(13, 0039f264, 00000000)
(EE) rt_sigaction() not implemented.
(II) sys_clock_gettime(1, 0x0039f474)
(II) sys_clock_gettime(1, 0x0039f3b4)
(II) sys_clock_gettime(1, 0x0039f3a4)
(II) poll(0x080829f8, 1, 1000)
(II) sys_clock_gettime(1, 0x0039f474)
(II) sys_clock_gettime(1, 0x0039f384)
(II) rt_sigaction(13, 00000000, 0039f260)
(EE) rt_sigaction() not implemented.
(II) rt_sigaction(13, 0039f1d4, 00000000)
(EE) rt_sigaction() not implemented.
</pre>

**Comment by wishstudio** [comment]
If this particular feature depends on signals, then clearly it won't work as signals are completely unsupported at this time.

**Comment by wishstudio** [comment]
Interestingly, the commit 8e640ae8c80d2327b0227c8fe97f971ce062e019 seems to unintentionally fix this issue. Could you please test if it works for you?

**Comment by bojieli** [comment]
Fantastic! It works.
