### ISSUE TITLE
Unsupported opcode

### ISSUE THREAD

**Issue by vitalyster** [wishstudio/flinux#33]
How to fix that? (I think it should be in wiki)
Got "unsupported opcode" with opcode=200 (BSWAP?) in archlinux gtk3-demo

**Comment by wishstudio** [comment]
x86 decoding is very complex. I didn't expect others to fix the instruction table ;-)
For opcode=200=0xC8, I suspect it's `ENTER` which is not supported (never seen usage). BSWAP (`0x0F 0xC8`) is already supported.

**Comment by wishstudio** [comment]
For gtk related stuff, it may not be actually an unsupported opcode error.
I've observed an issue with gtk query-immodules that it tries to unload a loaded module. It then loads another module which will reside in the same place. This causes dbt to fail as we don't support code unloading yet.

**Comment by wishstudio** [comment]
gtk3-demo works now.

There are still some crashes, but I think this issue is somewhat fixed.
