### ISSUE TITLE
Crash when I use zsh

### ISSUE THREAD

**Issue by wenjiahui** [wishstudio/flinux#35]
when I  installed zsh and switched to it,  crash occur after I run any command.

**Comment by wishstudio** [comment]
I think zsh uses rt_sigsuspend() to wait for SIGCHLD signal to wait for the child to terminate. rt_sigsuspend() is currently missing but I don't think add a stub will make it work properly.

**Comment by wenjiahui** [comment]
I prefer zsh with oh-my-zsh. so hope you fix it later

**Comment by timhieuungthu** [comment]
![image](https://cloud.githubusercontent.com/assets/11534690/6747309/0f65f10c-cf0a-11e4-8213-f94a277e5204.png)

**Comment by timhieuungthu** [comment]
http://benhvienungbuouhungviet.com/nguyen-nhan-benh-ung-thu-hach/

**Comment by timhieuungthu** [comment]
http://benhvienungbuouhungviet.com/ung-thu-vu/

**Comment by wishstudio** [comment]
@wenjiahui 
zsh should be usable for now. Could you please test it? You can get the latest development snapshot at https://ci.appveyor.com/project/wishstudio/flinux/build/artifacts.
