### ISSUE TITLE
su - crashes the application

### ISSUE THREAD

**Issue by jpfr** [wishstudio/flinux#4]
Hello @wishstudio 
running `su -` into the terminal crashes flinux.
I'm running on Windows 8 with the latest patches.

**Comment by HyperHCl** [comment]
Reproduced on Windows 7 x86.
flinux died with `FATAL: Unimplemented syscall: 206` in flog.

**Comment by wishstudio** [comment]
Permissions are not implemented at all at this stage.
Currently the user is always pid 0 (root) so you can do everything without the need of su/sudo.
I'm closing this for now.
