### ISSUE TITLE
crash when I use make

### ISSUE THREAD

**Issue by shaoxie1986** [wishstudio/flinux#47]
When I use make, it crashed.

**Comment by ahoka** [comment]
You can try using bmake as a workaround, you can install it from pacman.

**Comment by shaoxie1986** [comment]
it can use make-3.81 from compile myself.

**Comment by wishstudio** [comment]
Per my testing simple make scripts works on the latest version (get it at https://ci.appveyor.com/project/wishstudio/flinux/build/artifacts). Could you verify that?

**Comment by kika123** [comment]
bug fixed, yeah
