### ISSUE TITLE
Add assertion support.

### ISSUE THREAD

**Issue by wishstudio** [wishstudio/flinux#54]
Currently flinux code base lacks assertion code, which could greatly aid in debugging.
Since standard c IO functions cannot be safely used in flinux, we cannot use the standard assert() functions. We can instead implement our own in log.h and use flog for output.

**Comment by Incarnation-p-lee** [comment]
Still open for this issue ? or I may take some time to have a try.

**Comment by wishstudio** [comment]
Feel free to sent a PR for this. Thanks :smile:
