### ISSUE TITLE
Crash when running from Cmder

### ISSUE THREAD

**Issue by Sh4rK** [wishstudio/flinux#55]
I use Cmder (https://github.com/cmderdev/cmder) as it's much nicer than the basic cmd. However, flinux crashes immediatly with it trying to run anything. Flog: http://pastebin.com/yJsgUHZU

I traced down the cause: `mm_init` calls `mm_mmap` to allocate memory for the static alloc (`static_alloc_begin`). `mm_mmap` calls `mmap_internal`, which then calls `find_free_pages_topdown`, and there's where the error happens, as the returned address range is already partly `VirtualAlloc`-ed by something else (some part of Cmder). Then the `VirtualAlloc` obviously fails later on in `mmap_internal`.

I don't understand exactly how everything works, but shouldn't `find_free_pages_topdown` and `find_free_pages` check whether the memory regions are already allocated or not?

**Comment by wishstudio** [comment]
I believe this relates to issue #20 , which I planned to fix but haven't  :-p

Your guess is right, currently we don't check if the memory is actually available in `find_free_pages[_topdown]`.

My plan is to test the availability using VirtualQuery(), if the memory region is unavailable, create a special placeholder map_entry to avoid future confusions and restart.
