### ISSUE TITLE
could not change the root directory (No such file or directory)

### ISSUE THREAD

**Issue by kcrazy** [wishstudio/flinux#63]
`[root@ForeignLinux /]# pacman -Syu`
`:: Synchronizing package databases...`
 `core                                           120.0 KiB   930K/s 00:00 [########################################] 100%`
 `extra                                         1809.5 KiB  1146K/s 00:02 [########################################] 100%`
`community                                        2.8 MiB  1495K/s 00:02 [########################################] 100%`
`:: Starting full system upgrade...`
`resolving dependencies...`
`looking for conflicting packages...`

`Packages (1) libldap-2.4.42-2`

`Total Download Size:   0.29 MiB`
`Total Installed Size:  0.95 MiB`
`Net Upgrade Size:      0.00 MiB`

`:: Proceed with installation? [Y/n]`
`:: Retrieving packages ...`
`libldap-2.4.42-2-i686                          299.1 KiB   956K/s 00:00 [########################################] 100%`
`(1/1) checking keys in keyring                                           [########################################] 100%`
`(1/1) checking package integrity                                         [########################################] 100%`
`(1/1) loading package files                                              [########################################] 100%`
`(1/1) checking for file conflicts                                        [########################################] 100%`
`(1/1) checking available disk space                                      [########################################] 100%`
`(1/1) upgrading libldap                                                  [########################################] 100%`
`could not change the root directory (No such file or directory)`
`error: command failed to execute correctly`
`[root@ForeignLinux /]#`

**Comment by wishstudio** [comment]
Roughly equivalent to issue #59
