### ISSUE TITLE
Several crashes during ./configure

### ISSUE THREAD

**Issue by factormystic** [wishstudio/flinux#66]
Again this is part of trying to build ruby from source.

Running autoconf then ./configure you can see that there's several Windows crash reporting dialogs during this. I don't really want to post the flog dump because most configure steps work and it'd be a really low signal-noise ratio. But if you run the same commands you should also see this behavior.

**Comment by wishstudio** [comment]
Could you observe this behavior anymore?
I made a mistake that a left over __debugbreak() is pushed. It will crash when dbt code cache is being flushed.

**Comment by factormystic** [comment]
Yep all good
