### ISSUE TITLE
Windows 7 compatibility

### ISSUE THREAD

**Issue by SaphireLattice** [wishstudio/flinux#68]
Any chance for flinux to have at least some limited releases for win 7? Or does it (flinux) requires some win8 and later features deep in it's core?

**Comment by wishstudio** [comment]
To support multi-threading (specifically futex(2)), flinux need the API WaitOnAddress() and friends introduced in Win8. We can, for example, make these dynamic loaded functions and disable multi-threading when these functions are not found. But there are really too many things requiring threading support.

So tl;dr version is, unless Microsoft adds these calls to win7 (which is unlikely to happen), supporting win7 does not make much sense.

**Comment by wishstudio** [comment]
I have implemented `futex(2)` using non win8 specific functions. Should be able to regain support for win7 soon.

**Comment by wishstudio** [comment]
Fixed.
