### ISSUE TITLE
Is it possible to run archlinux's `xorg-server`?

### ISSUE THREAD

**Issue by flyskywhy** [wishstudio/flinux#81]
After `pacman -S xorg-server xorg-server-utils xorg-xinit xf86-video-vesa`, when `startx`, `flinux.exe` crashed.
Even #9 said we can use some X servers for Windows like Xming, I still wonder if it's possible to run archlinux's `xorg-server`?

**Comment by wishstudio** [comment]
Basically it's impossible currently. xorg-server need to call system's graphics driver to deliver graphics output. As we're a purely emulated environment we never have direct hardware. So unless we emulate such using software techniques we won't be able to support an x server.
