### ISSUE TITLE
how to I run x programs?

### ISSUE THREAD

**Issue by ericfont** [wishstudio/flinux#9]
When I install and run xeyes, I get: 

```
[root@ForeignLinux /]# xeyes
Error: Can't open display: 127.0.0.1:0
```

Do I need to setup an xorg server or do something else like forwarding to another xorg server?

**Comment by nilsding** [comment]
To run X applications, a running X server is required.  There are some X servers for Windows, the most common seems to be [Xming](http://www.straightrunning.com/XmingNotes/).

You can also set the `DISPLAY` environment variable to forward it to another running X11 server:

```
$ export DISPLAY=172.16.0.12:0
```

**Comment by wishstudio** [comment]
Not a real issue.
